node_id=1
node_name='wezel1'

conninfo='host=wezel1 user=repmgr dbname=repmgr password=haslo'

data_directory='/var/lib/postgresql/18/data'

failover=automatic
promote_command='repmgr standby promote -f /etc/repmgr.conf'
follow_command='repmgr standby follow -f /etc/repmgr.conf'

data_directory='/var/lib/postgresql/18/data'

service_start_command='pg_ctl -D /var/lib/postgresql/18/data start'
service_stop_command='pg_ctl -D /var/lib/postgresql/18/data stop'
service_restart_command='pg_ctl -D /var/lib/postgresql/18/data restart'
