node_id=1
node_name='wezel1'
conninfo='host=wezel1 user=repmgr dbname=repmgr password=haslo connect_timeout=2'
data_directory='/var/lib/postgresql/18/data'
failover='automatic'
promote_command='repmgr standby promote -f /etc/repmgr.conf'
follow_command='repmgr standby follow -f /etc/repmgr.conf' # <--- DODAJ TĘ LINIJKĘ!
reconnect_attempts=3
reconnect_interval=10
