node_id=2
node_name='wezel2'
conninfo='host=wezel2 user=repmgr dbname=repmgr password=haslo connect_timeout=2'
data_directory='/var/lib/postgresql/18/data'
failover='automatic'
promote_command='repmgr standby promote -f /etc/repmgr.conf'
follow_command='repmgr standby follow -f /etc/repmgr.conf'
reconnect_attempts=3
reconnect_interval=10
